global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "vllm"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.86.173:8000"]
        labels:
          node: "gpu-node-1"
      - targets: ["192.168.86.176:8000"]
        labels:
          node: "gpu-node-2"

  - job_name: "dcgm"
    static_configs:
      - targets: ["192.168.86.173:9400"]
        labels:
          node: "gpu-node-1"
      - targets: ["192.168.86.176:9400"]
        labels:
          node: "gpu-node-2"

  - job_name: "node"
    static_configs:
      - targets: ["192.168.86.173:9100"]
        labels:
          node: "gpu-node-1"
      - targets: ["192.168.86.176:9100"]
        labels:
          node: "gpu-node-2"
